[package]
name = "usb-io"
version = "0.1.0"
edition = "2021"
authors = ["no111u3"]

[dependencies]
postcard = "1"
serde = { version = "1", default-features = false }
usb-device = "0.2"
rusb = { version = "0.9.1", optional = true }

[features]
std = ["dep:rusb"]
default = ["std"]